package com.example.ui.theme

import androidx.compose.ui.graphics.Color

enum class AppEditorTheme(
    val id: String,
    val displayName: String,
    val description: String,
    val background: Color,
    val sidebarBg: Color,
    val titleBarBg: Color,
    val statusBarBg: Color,
    val tabActiveBg: Color,
    val tabInactiveBg: Color,
    val accentColor: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val border: Color,
    val gutterBg: Color,
    val keywordColor: Color,
    val controlKeywordColor: Color,
    val stringColor: Color,
    val numberColor: Color,
    val commentColor: Color,
    val tagColor: Color,
    val attributeColor: Color,
    val functionColor: Color
) {
    OBSIDIAN_DARK(
        id = "obsidian_dark",
        displayName = "Obsidian Dark",
        description = "Deep matte dark palette with electric cyan accents",
        background = Color(0xFF101216),
        sidebarBg = Color(0xFF16191F),
        titleBarBg = Color(0xFF1A1D24),
        statusBarBg = Color(0xFF21262D),
        tabActiveBg = Color(0xFF101216),
        tabInactiveBg = Color(0xFF16191F),
        accentColor = Color(0xFF388BFD),
        textPrimary = Color(0xFFE6EDF3),
        textSecondary = Color(0xFF8B949E),
        border = Color(0xFF282C34),
        gutterBg = Color(0xFF101216),
        keywordColor = Color(0xFF79C0FF),
        controlKeywordColor = Color(0xFFD2A8FF),
        stringColor = Color(0xFFA5D6FF),
        numberColor = Color(0xFF7EE787),
        commentColor = Color(0xFF6E7681),
        tagColor = Color(0xFF79C0FF),
        attributeColor = Color(0xFFFFA657),
        functionColor = Color(0xFFD2A8FF)
    ),

    ONE_DARK(
        id = "one_dark",
        displayName = "One Dark",
        description = "Vibrant pastel accents on deep twilight surfaces",
        background = Color(0xFF282C34),
        sidebarBg = Color(0xFF21252B),
        titleBarBg = Color(0xFF21252B),
        statusBarBg = Color(0xFF323640),
        tabActiveBg = Color(0xFF282C34),
        tabInactiveBg = Color(0xFF21252B),
        accentColor = Color(0xFF61AFEF),
        textPrimary = Color(0xFFABB2BF),
        textSecondary = Color(0xFF7F848E),
        border = Color(0xFF1B1D23),
        gutterBg = Color(0xFF282C34),
        keywordColor = Color(0xFFE06C75),
        controlKeywordColor = Color(0xFFC678DD),
        stringColor = Color(0xFF98C379),
        numberColor = Color(0xFFD19A66),
        commentColor = Color(0xFF5C6370),
        tagColor = Color(0xFFE06C75),
        attributeColor = Color(0xFFD19A66),
        functionColor = Color(0xFF61AFEF)
    ),

    DRACULA(
        id = "dracula",
        displayName = "Dracula",
        description = "Neon cyberpunk contrast with purple and emerald tones",
        background = Color(0xFF282A36),
        sidebarBg = Color(0xFF21222C),
        titleBarBg = Color(0xFF191A21),
        statusBarBg = Color(0xFF383A59),
        tabActiveBg = Color(0xFF282A36),
        tabInactiveBg = Color(0xFF21222C),
        accentColor = Color(0xFFBD93F9),
        textPrimary = Color(0xFFF8F8F2),
        textSecondary = Color(0xFF6272A4),
        border = Color(0xFF44475A),
        gutterBg = Color(0xFF282A36),
        keywordColor = Color(0xFFFF79C6),
        controlKeywordColor = Color(0xFFFF79C6),
        stringColor = Color(0xFFF1FA8C),
        numberColor = Color(0xFFBD93F9),
        commentColor = Color(0xFF6272A4),
        tagColor = Color(0xFFFF79C6),
        attributeColor = Color(0xFF50FA7B),
        functionColor = Color(0xFF8BE9FD)
    ),

    MONOKAI_PRO(
        id = "monokai_pro",
        displayName = "Monokai Pro",
        description = "Warm amber and chartreuse highlights on dark charcoal",
        background = Color(0xFF2D2A2E),
        sidebarBg = Color(0xFF221F22),
        titleBarBg = Color(0xFF19181A),
        statusBarBg = Color(0xFF363337),
        tabActiveBg = Color(0xFF2D2A2E),
        tabInactiveBg = Color(0xFF221F22),
        accentColor = Color(0xFFFFD866),
        textPrimary = Color(0xFFFCFCFA),
        textSecondary = Color(0xFF939293),
        border = Color(0xFF403E41),
        gutterBg = Color(0xFF2D2A2E),
        keywordColor = Color(0xFFFF6188),
        controlKeywordColor = Color(0xFFFF6188),
        stringColor = Color(0xFFFFD866),
        numberColor = Color(0xFFAB9DF2),
        commentColor = Color(0xFF727072),
        tagColor = Color(0xFFFF6188),
        attributeColor = Color(0xFF78DCE8),
        functionColor = Color(0xFFA9DC76)
    ),

    NIGHT_OWL(
        id = "night_owl",
        displayName = "Night Owl",
        description = "Deep midnight navy with electric blue and coral accents",
        background = Color(0xFF011627),
        sidebarBg = Color(0xFF010E1A),
        titleBarBg = Color(0xFF010E1A),
        statusBarBg = Color(0xFF082238),
        tabActiveBg = Color(0xFF011627),
        tabInactiveBg = Color(0xFF010E1A),
        accentColor = Color(0xFF82AAFF),
        textPrimary = Color(0xFFD6DEEB),
        textSecondary = Color(0xFF5F7E97),
        border = Color(0xFF112638),
        gutterBg = Color(0xFF011627),
        keywordColor = Color(0xFFC792EA),
        controlKeywordColor = Color(0xFFC792EA),
        stringColor = Color(0xFFECC48D),
        numberColor = Color(0xFFF78C6C),
        commentColor = Color(0xFF637777),
        tagColor = Color(0xFF7FDBCA),
        attributeColor = Color(0xFFFAD430),
        functionColor = Color(0xFF82AAFF)
    )
}
